spring:
  datasource:
    url: jdbc:mysql://localhost:3306/voice_order?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Shicong666
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.cleveronion.voiceorderdemoback: DEBUG

openai:
  api:
    key: "sk-e03282d1160e46929821a51a090a765e"
  base-url: "https://api.deepseek.com"
  model-name: "deepseek-chat"