spring:
  datasource:
    url: jdbc:mysql://localhost:3306/voice_order?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Shicong666
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.cleveronion.voiceorderdemoback: DEBUG
  charset:
    console: utf-8

openai:
  api:
    key: "e9f1e652-2214-41e0-8c20-e38f6b66e437"
  base-url: "https://ark.cn-beijing.volces.com/api/v3"
  model-name: "deepseek-v3-241226"